### PR TITLE
Add Ocr options for preview sizes, enable tap to capture text

### PR DESCRIPTION
**Pull request by cybaker**

### CODE REVIEW

**Comment by edufolly** [comment]
Hi @cybaker, it's a great job!

Maybe is better to pass the preview size as an integer and control the size options in the app. This will improve the flexibility of the plugin. What do you think about it?

**Comment by cybaker** [comment]
Hi edufolly. I thought about that - Flutter would then need to access the hardware camera properties in order to select the right size to pass back. I decided not to do that at this point since I was needing only the 640x480 mode. I'm guessing the one additional API would be to return a list of sizes to Flutter given the camera device number (facing back or forward), then Flutter can pick the size and send back the width and height it desires. What do you think?

**Comment by edufolly** [comment]
I would like to get the camera sizes through an API. Do you know how we can do this?

**Comment by cybaker** [comment]
Yes, I've done the Java before for preview size. Looks like https://github.com/flutter/plugins/tree/master/packages/camera has done this already. Maybe it's better to use that library and integrate ML Kit into it somehow. Else we can use it's preview size way.

**Comment by cybaker** [comment]
Unfortunately they use the same single value pass with 3 options just like mine. I'll see if I can get a List<Size> passed back, and pass in a Size.

**Comment by cybaker** [comment]
Any comment about this PR? No activity for almost 2 months.

**Comment by edufolly** [comment]
Sorry I'll analyze this PR now.

**Pull request merged**
